features = {
    "DS_numerical": [
        'CM Age last birthday',
        'Height in centimeters',
        'Weight in kilos',
        'Body fat percentage',
        'Days last week spent doing moderate to vigorous physical activity',
        'Hours per WEEKDAY spent watching TV or videos on computer',
        'Hours per WEEKDAY spent playing electronic games',
        'Hours per week spent on social networking sites',
        'How likely is it CM will remain in education at the end of year 11?',
        'How likely is it CM will go to university? (Scale 0-100%)',
        'How willing is CM to take risks',
        'How patient is CM',
        'How much does CM trust others'
    ],

    "DS_cat_nominal": [
        'CM Sex',
        'Respondent s religion (A) [England]',
        'Left/Right handed?',
        'What type of bread does CM normally eat'
    ],

    "DS_cat_ordinal_lowest_num_is_highest_value": [
        'ActivGrid: Go to the cinema?',
        'ActivGrid: Go to watch live sport?',
        'ActivGrid: Sing in a choir or play in a band or orchestra?',
        'ActivGrid: Read for enjoyment (not for school)?',
        'ActivGrid: Go to youth clubs/scouts/girlguides or oth organised activities?',
        'ActivGrid: Go to museums/galleries, visit historic place/stately home?',
        'ActivGrid: Attend a religious service?',
        'Do you allow unsupervised time outside home with frds (on weekends)',
        'Do you allow unsupervised time outside home with frds (afternoon after school)',
        'MoralAttGrid: How important is it to you to be well liked?',
        'MoralAttGrid: How important is it to you to work hard?',
        'Wrong to start a fight',
        'Wrong to write or spray paint on building/fence etc',
        'Wrong to take things without paying',
        'Wrong to download music/films/games without paying',
        "How often does anyone at home help with CM's homework",
        'EducMotGrid: How often do you try your best at school?',
        'EducMotGrid: How often do you find school interesting?',
        'EducMotGrid: How often do you feel unhappy at school?',
        'EducMotGrid: How often do you get tired at school?',
        'EducMotGrid: How often do you feel school is a waste of time?',
        'EducMotGrid: How often difficult to keep mind on work at school? [NCDS, BCS]',
        'How often does CM misbehave in lessons',
        'How often does CM argue with mother',
        'How often does CM argue with father',
        'When CM goes out, how often do parents know where?',
        'When CM goes out, how often do parents know who with?',
        'When CM goes out, how often do parents know what CM does?',
        'How often do you see any of your grandparents?',
        'How many of your close friends go to the same school as you?',
        'How many of your close friends are boys?',
        'How many of your close friends are girls?',
        'How many of your close friends are from the same ethnic group as you?',
        'How many of your close friends work hard at school?',
        'How many of your close friends get into a lot of trouble at school?',
        'How often brothers or sisters hurt or pick on CM',
        'How often CM hurts or picks on brothers or sisters',
        'How often other children hurt or pick on CM',
        'How often CM hurts or picks on other children',
        'How often other children bullied CM online',
        'How often CM bullied other children online',
        'How often does CM drink artifically sweetened drinks',
        'How often does CM eat fast food',
        "CM's general level of health",
        'During the last 4 weeks how often did CM awaken during sleep',
        'WellbeingGrid: How happy is CM with the way they look',
        'WellbeingGrid: How happy is CM with family',
        'WellbeingGrid: How happy is CM with friends',
        'WellbeingGrid: How happy is CM with school',
        'WellbeingGrid: How happy is CM with life as a whole',
        'RosenbergGrid: On the whole, I am satisfied with myself',
        'RosenbergGrid: I feel I have a number of good qualities',
        'RosenbergGrid: I am able to do things as well as most other people',
        'RosenbergGrid: I am a person of value',
        'RosenbergGrid: I feel good about myself',
        'SocSupGrid: I have family and friends who help me feel safe, secure and happy.',
        'SocSupGrid: There is someone I trust whom I would turn to if I had problems',
        "ConsumAttGrid: It bothers me if my friends have things I don't",
        'Needs qualifications to get a job worth having'
    ],

    "DS_cat_ordinal_highest_num_is_highest_value": [
        'Does CM ever use the internet at home',
        'typical week term-time, how long cm spends doing homework?',
        'How close is CM with mother',
        'How close is CM with father',
        'How often CM smokes e-cigarettes',
        "How many of CM's friends drink alcohol",
        "Do CM's friends take any illegal drugs",
        'Past month: freq of CM staying out (9pm+) without Parent knowing',
        'How often CM eats at least 2 portions of fruit',
        'Time CM goes to sleep on a school night',
        'Time CM wakes up on a school day',
        'Time CM wakes up when there is no school',
        'During the last 4 weeks how long does going to sleep usually take',
        "CM's perception of their weight",
        'CM growth spurt',
        'CM skin changes eg spots',
        "How often CM's friends smoke cigarettes",
        'AcademicSelfConceptGrid: I am good at English',
        'AcademicSelfConceptGrid: I am good at Maths',
        'AcademicSelfConceptGrid: I am good at Science',
        'AcademicSelfConceptGrid: I am good at PE'
    ],

    "DS_cat_nominal_binary_Y1_N2": [
        'Does CM have computer of their own',
        'Has CM has any formal cycle training',
        'Quiet area where CM is able to do homework',
        "Has CM missed school without parents' permission",
        'DisciplineGrid: Tell you off or shout at you?',
        'DisciplineGrid: Ground you, stop you going out or from seeing your friends?',
        'DisciplineGrid: Punish you in some other way?',
        'Does your natural father live with you?',
        'Do you have any close friends? (friends = other young people)',
        'Has CM ever been attracted to a male',
        '(last 12 months) has CM held hands with another young person?',
        '(last 12 months) has CM kissed another young person?',
        '(last 12 months) has CM cuddled with another young person?',
        '(last 12 months) has CM had sexual intercourse with another YP?',
        'Has CM ever had an alcoholic drink',
        'DruGrid: Cannabis (also known as weed, marijuana, dope, hash or skunk)?',
        'GamblinGrid: Placing a private bet for money (e.g. with friends)?',
        'GamblinGrid: Placing a bet @ betting shop, eg football or horseracing?',
        'VictimisGrid: CM insulted, threatened, shouted at',
        'VictimisGrid: been physically violent towards CM',
        'VictimisGrid: hit or used a weapon against CM',
        'VictimisGrid: stolen something from CM',
        'VictimisGrid: sexually assaulted CM',
        'Has CM ever entered someones home to steal or damage something',
        'ASBOgrid: CM Pushed or shoved/hit/slapped/punched someone?',
        'ASBOgrid: CM Used or hit someone with a weapon?',
        'ASBOgrid: CM stolen something from someone eg mobile phone, money',
        'Has CM been stopped or questioned by police',
        'Has CM ever been given a formal warning or caution from police',
        'Has CM ever been arrested',
        'Past 12 months: has CM sent viruses to damage/infect other computers',
        'Does CM wear glasses or contact lenses',
        'Does CM have difficulty seeing',
        'Does CM have difficulty hearing',
        'Has CM been to a dentist in last 12 months',
        'Has CM ever exercised to lose weight',
        'Has CM ever eaten less to lose weight',
        'In the past year has CM self-harmed'
    ],

    "DS_cat_nominal_binary_Y1_N0": [
        'Where CM gets spending money from MC (A) [Regular pocket money/allowance]',
        'Where CM gets spending money from MC (A) [Chores/babysitting]',
        'Where CM gets spending money from MC (A) [Working in the family business]',
        'Where CM gets spending money from MC (A) [Paid job]',
        'Where CM gets spending money from MC (A) [Parents given when CM needs]',
        'Where CM gets spending money from MC (A) [Never get any money to spend]',
        'Where CM gets spending money from MC (A) [Money from friends/relatives]',
        'Where CM gets spending money from MC (A) [Money frm spcl occasins BirthD/Xmas]',
        'Where CM gets spending money from MC (A) [Reward for good behaviour/grades]',
        'Where CM gets spending money from MC (A) [Money for school]',
        'Where CM gets spending money from MC (A) [From selling items]',
        'Where CM gets spending money from MC (A) [Saving]',
        'Where CM gets spending money from MC (A) [Other earnings]',
        'Who decided next year subjects (Parents)',
        'Who decided next year subjects (School/teachers)',
        'Who decided next year subjects (You, yourself)',
        'Who decided next year subjects (Someone else)',
        'Area safety: safe for CM to walk/play etc within a mile/20 min from home',
        'Languages used speaking with friends MC (A) [English]',
        'Languages used speaking with friends MC (A) [Gaelic]',
        'Languages used speaking with friends MC (A) [Urdu]',
        'Languages used speaking with friends MC (A) [Punjabi]',
        'Languages used speaking with friends MC (A) [Hindi]',
        'Languages used speaking with friends MC (A) [Bengali]',
        'Languages used speaking with friends MC (A) [Sylheti]',
        'Languages used speaking with friends MC (A) [Tamil]',
        'Languages used speaking with friends MC (A) [Turkish]',
        'Languages used speaking with friends MC (A) [Arabic]',
        'Languages used speaking with friends MC (A) [Other]',
        'Languages used speaking with friends MC (A) [Other European language]',
        'Languages used speaking with friends MC (A) [Other African language]',
        'Languages used speaking with friends MC (A) [Other Asian language]',
        'What do you do if you are worried about something?',
        'What do you do if you are worried about smthng? (Tell a (boy/girl) friend)',
        'What do you do if you are worried about something? (Tell another relative)',
        'What do you do if you are worried about something? (Tell a teacher)',
        'What do you do if you are worried about something? (Tell another adult)',
        'What do you do if you are worried about something? (Keep it to myself)'
    ]
}
